version: "3.6"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./keycloak/data/:/opt/jboss/keycloak/standalone/data/
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001 
  edgeserver:
    build: ./
    command: python3 EdgeServer.py
    ports:
      - 5000:5000
    depends_on:
      - keycloak
      - redis
      - mosquitto
    links:
      - keycloak
      - redis
      - mosquitto



      