version: "3.6"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./DockerComposeFiles/definitions.json:/srv/definitions.json
      # - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./DockerComposeFiles/rabbitmq.conf:/etc/rabbitmq/conf.d/10-default-guest-user.conf
      - ./DockerComposeFiles/enabled_plugins.txt:/etc/rabbitmq/enabled_plugins